version: '3.7'

services:
  eventstore.db:
    image: eventstore/eventstore:20.10.0-buster-slim
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "2113:2113"
  mong.db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=projections
    ports:
      - "27017-27019:27017-27019"